---
- name: Install s3cmd
  ansible.builtin.apt:
    name: s3cmd
    state: present

- name: S3CMD | Configuration
  template:
    src: user_s3
    dest: ~/.s3cfg

- name: S3CMD | Put backup 
  shell: s3cmd put -e --storage-class=DEEP_ARCHIVE --recursive /caminho-backup s3://bucket-name

- name: S3CMD | Remove .s3cfg
  ansible.builtin.file:
    path: ~/.s3cfg
    state: absent